[package]
name = "tamiacoin-program"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

[lib]
path = "src/lib.rs"

[features]
no-entrypoint = []
cpi = []
custom-heap = []
custom-panic = []
anchor-debug = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
incremental = true
codegen-units = 16

[profile.release]
opt-level = 3
debug = false
overflow-checks = true
lto = "fat"
codegen-units = 1
incremental = false
